### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Wulfheart** [prewk/option#15]

**Comment by prewk** [comment]
Whoops! Can you PR this and the `Result` repo with it? I'll merge and tag.

**Comment by prewk** [comment]
There, I've clarified the licenses in 3.1.1.

**Comment by prewk** [comment]
Lock file issues, updated deps and released 3.2.0.

**Comment by prewk** [comment]
Sigh, a world of hurt to re-visit old stuff. Oh well, 3.3.0 passes most CI anyway.
